name: step_model2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.9
  - pip:
      - opencv-python
      - pandas
      - simplejson
      - timm==0.9.10
      - torch==1.13.1
      - torchvision==0.14.1
      - tqdm
      - numpy==1.24.4
      - lmdb
      - distinctipy
      - einops
      - matplotlib
      - tensorboard
      - yacs
      - wandb
      - scikit-learn
